-- Leco MVP foundation.
-- Exact locations are intentionally isolated in public.user_locations. They must
-- only be consumed through the security-definer RPCs defined in this migration.

create schema if not exists extensions;
create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon, authenticated;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists postgis with schema extensions;

create type public.gender as enum (
  'woman',
  'man',
  'non_binary',
  'other',
  'prefer_not_to_say'
);

create type public.account_status as enum (
  'active',
  'deactivated',
  'suspended',
  'pending_deletion'
);

create type public.availability_status as enum (
  'offline',
  'available',
  'hidden'
);

create type public.mood as enum (
  'sortir',
  'discuter',
  'manger',
  'match',
  'rencontre',
  'sport',
  'evenement',
  'plan_tranquille'
);

create type public.distance_band as enum (
  'TOUT_PRES',
  'MOINS_DE_500_M',
  'ENTRE_500_M_ET_1_KM',
  'DANS_TON_SECTEUR'
);

create type public.like_status as enum (
  'pending',
  'matched',
  'cancelled',
  'expired'
);

create type public.match_status as enum (
  'active',
  'ended',
  'blocked'
);

create type public.report_reason as enum (
  'harassment',
  'threat',
  'fake_profile',
  'impersonation',
  'potential_minor',
  'unsolicited_sexual_content',
  'spam',
  'scam',
  'hate',
  'other'
);

create type public.report_status as enum (
  'open',
  'in_review',
  'resolved',
  'dismissed'
);

create type public.moderation_action_type as enum (
  'warning',
  'temporary_suspension',
  'permanent_suspension',
  'content_removal',
  'report_dismissal',
  'account_reinstatement'
);

create table public.profiles (
  id uuid primary key references auth.users (id) on delete restrict,
  first_name text,
  birth_date date,
  gender public.gender,
  searching_for public.gender[] not null default '{}'::public.gender[],
  bio text,
  account_status public.account_status not null default 'active',
  is_discoverable boolean not null default true,
  is_profile_complete boolean not null default false,
  suspended_until timestamptz,
  deletion_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_first_name_length
    check (first_name is null or char_length(btrim(first_name)) between 1 and 50),
  constraint profiles_bio_length
    check (bio is null or char_length(bio) <= 150),
  constraint profiles_searching_for_limit
    check (cardinality(searching_for) <= 5),
  constraint profiles_suspension_consistency
    check (account_status = 'suspended' or suspended_until is null),
  constraint profiles_deletion_consistency
    check (
      (account_status = 'pending_deletion' and deletion_requested_at is not null)
      or (account_status <> 'pending_deletion' and deletion_requested_at is null)
    )
);

comment on column public.profiles.birth_date is
  'Private profile attribute. Public discovery returns calculated age only.';

create table public.profile_photos (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  cloudinary_public_id text not null,
  cloudinary_version integer,
  secure_url text not null,
  sort_order smallint not null,
  width integer,
  height integer,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint profile_photos_public_id_length
    check (char_length(cloudinary_public_id) between 1 and 255),
  constraint profile_photos_https_url
    check (secure_url ~ '^https://'),
  constraint profile_photos_sort_order
    check (sort_order between 1 and 4),
  constraint profile_photos_dimensions
    check (
      (width is null and height is null)
      or (width is not null and height is not null and width > 0 and height > 0)
    )
);

create unique index profile_photos_active_order_unique
  on public.profile_photos (profile_id, sort_order)
  where deleted_at is null;

create unique index profile_photos_active_public_id_unique
  on public.profile_photos (cloudinary_public_id)
  where deleted_at is null;

create index profile_photos_profile_id_idx
  on public.profile_photos (profile_id, sort_order)
  where deleted_at is null;

create table public.interests (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label_fr text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint interests_slug_format
    check (slug ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$'),
  constraint interests_label_length
    check (char_length(btrim(label_fr)) between 1 and 50)
);

create table public.user_interests (
  user_id uuid not null references public.profiles (id) on delete cascade,
  interest_id bigint not null references public.interests (id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (user_id, interest_id)
);

create index user_interests_interest_id_idx
  on public.user_interests (interest_id, user_id);

create table public.user_locations (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  location extensions.geography(Point, 4326) not null,
  accuracy_m real,
  captured_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  updated_at timestamptz not null default now(),
  constraint user_locations_accuracy_range
    check (accuracy_m is null or accuracy_m between 0 and 10000),
  constraint user_locations_expiry
    check (expires_at > captured_at and expires_at <= captured_at + interval '30 minutes')
);

comment on table public.user_locations is
  'Current exact position only. No location history; never select this table from a client.';

create index user_locations_geography_gist_idx
  on public.user_locations using gist (location);

create index user_locations_expiry_idx
  on public.user_locations (expires_at);

create table public.user_presence (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  availability_status public.availability_status not null default 'offline',
  mood public.mood,
  last_heartbeat_at timestamptz,
  activated_at timestamptz,
  available_until timestamptz,
  updated_at timestamptz not null default now(),
  constraint user_presence_available_state
    check (
      (
        availability_status = 'available'
        and mood is not null
        and last_heartbeat_at is not null
        and activated_at is not null
        and available_until is not null
        and available_until > activated_at
      )
      or (
        availability_status <> 'available'
        and mood is null
        and activated_at is null
        and available_until is null
      )
    )
);

create index user_presence_discovery_idx
  on public.user_presence (availability_status, available_until, last_heartbeat_at)
  where availability_status = 'available';

create table public.likes (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles (id) on delete restrict,
  recipient_id uuid not null references public.profiles (id) on delete restrict,
  status public.like_status not null default 'pending',
  created_at timestamptz not null default now(),
  matched_at timestamptz,
  resolved_at timestamptz,
  constraint likes_distinct_users
    check (sender_id <> recipient_id),
  constraint likes_match_timestamp
    check (
      (status = 'matched' and matched_at is not null)
      or (status <> 'matched' and matched_at is null)
    ),
  constraint likes_resolution_timestamp
    check (
      (status in ('cancelled', 'expired') and resolved_at is not null)
      or (status not in ('cancelled', 'expired') and resolved_at is null)
    )
);

create unique index likes_one_pending_per_direction_idx
  on public.likes (sender_id, recipient_id)
  where status = 'pending';

create index likes_sender_rate_limit_idx
  on public.likes (sender_id, created_at desc);

create index likes_recipient_pending_idx
  on public.likes (recipient_id, created_at desc)
  where status = 'pending';

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  user_low_id uuid not null references public.profiles (id) on delete restrict,
  user_high_id uuid not null references public.profiles (id) on delete restrict,
  status public.match_status not null default 'active',
  matched_at timestamptz not null default now(),
  ended_at timestamptz,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matches_canonical_participant_order
    check (user_low_id::text < user_high_id::text),
  constraint matches_end_timestamp
    check (
      (status = 'active' and ended_at is null)
      or (status <> 'active' and ended_at is not null)
    ),
  unique (user_low_id, user_high_id)
);

create index matches_user_low_activity_idx
  on public.matches (user_low_id, last_message_at desc nulls last, matched_at desc);

create index matches_user_high_activity_idx
  on public.matches (user_high_id, last_message_at desc nulls last, matched_at desc);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches (id) on delete restrict,
  sender_id uuid not null references public.profiles (id) on delete restrict,
  content text not null,
  content_hash bytea generated always as (
    extensions.digest(
      lower(regexp_replace(btrim(content), '\s+', ' ', 'g')),
      'sha256'
    )
  ) stored,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  deleted_at timestamptz,
  constraint messages_text_only_length
    check (char_length(btrim(content)) between 1 and 2000),
  constraint messages_read_timestamp
    check (read_at is null or read_at >= created_at),
  constraint messages_deleted_timestamp
    check (deleted_at is null or deleted_at >= created_at)
);

comment on column public.messages.content_hash is
  'Normalized one-way hash used for repeated-message abuse detection.';

create index messages_match_timeline_idx
  on public.messages (match_id, created_at desc);

create index messages_sender_duplicate_idx
  on public.messages (sender_id, content_hash, created_at desc);

create table public.blocks (
  id uuid primary key default gen_random_uuid(),
  blocker_id uuid not null references public.profiles (id) on delete restrict,
  blocked_id uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint blocks_distinct_users
    check (blocker_id <> blocked_id),
  unique (blocker_id, blocked_id)
);

create index blocks_blocked_id_idx
  on public.blocks (blocked_id, blocker_id);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete restrict,
  reported_user_id uuid not null references public.profiles (id) on delete restrict,
  match_id uuid references public.matches (id) on delete restrict,
  message_id uuid references public.messages (id) on delete restrict,
  reason public.report_reason not null,
  description text,
  status public.report_status not null default 'open',
  moderator_decision text,
  reviewed_by uuid references public.profiles (id) on delete restrict,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reports_distinct_users
    check (reporter_id <> reported_user_id),
  constraint reports_description_length
    check (description is null or char_length(description) <= 1000),
  constraint reports_decision_length
    check (moderator_decision is null or char_length(moderator_decision) <= 2000),
  constraint reports_review_consistency
    check (
      (status in ('resolved', 'dismissed') and reviewed_by is not null and reviewed_at is not null)
      or (status not in ('resolved', 'dismissed') and reviewed_by is null and reviewed_at is null)
    )
);

create index reports_moderation_queue_idx
  on public.reports (status, created_at);

create index reports_reported_user_idx
  on public.reports (reported_user_id, created_at desc);

create table public.moderation_actions (
  id uuid primary key default gen_random_uuid(),
  report_id uuid references public.reports (id) on delete restrict,
  moderator_id uuid not null references public.profiles (id) on delete restrict,
  target_user_id uuid not null references public.profiles (id) on delete restrict,
  action_type public.moderation_action_type not null,
  rationale text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  constraint moderation_actions_rationale_length
    check (char_length(btrim(rationale)) between 1 and 2000),
  constraint moderation_actions_expiry
    check (expires_at is null or expires_at > created_at)
);

create index moderation_actions_target_idx
  on public.moderation_actions (target_user_id, created_at desc);

create index moderation_actions_report_idx
  on public.moderation_actions (report_id)
  where report_id is not null;

create table public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles (id) on delete restrict,
  event_type text not null,
  target_table text,
  target_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint audit_logs_event_type_format
    check (event_type ~ '^[a-z0-9]+(?:[._][a-z0-9]+)*$'),
  constraint audit_logs_metadata_object
    check (jsonb_typeof(metadata) = 'object')
);

comment on table public.audit_logs is
  'Append-only administrative audit trail. Metadata must exclude secrets, coordinates and message bodies.';

create index audit_logs_occurred_at_brin_idx
  on public.audit_logs using brin (occurred_at);

create index audit_logs_actor_idx
  on public.audit_logs (actor_id, occurred_at desc)
  where actor_id is not null;

create table private.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  constraint app_settings_key_format
    check (key ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$')
);

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := statement_timestamp();
  return new;
end;
$$;

create or replace function private.validate_profile_age()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.birth_date is not null then
    if new.birth_date > current_date - interval '18 years' then
      raise exception using
        errcode = '22023',
        message = 'profile owner must be at least 18 years old';
    end if;

    if new.birth_date < current_date - interval '100 years' then
      raise exception using
        errcode = '22023',
        message = 'birth date is outside the accepted range';
    end if;
  end if;

  new.first_name := nullif(btrim(new.first_name), '');
  new.bio := nullif(btrim(new.bio), '');
  return new;
end;
$$;

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

create or replace function private.refresh_profile_completion(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_photo_count integer;
  v_interest_count integer;
begin
  select count(*)::integer
  into v_photo_count
  from public.profile_photos
  where profile_id = p_user_id
    and deleted_at is null;

  select count(*)::integer
  into v_interest_count
  from public.user_interests
  where user_id = p_user_id;

  update public.profiles
  set is_profile_complete = (
    first_name is not null
    and birth_date is not null
    and gender is not null
    and cardinality(searching_for) between 1 and 5
    and v_photo_count between 2 and 4
    and v_interest_count between 2 and 3
  )
  where id = p_user_id;
end;
$$;

create or replace function private.enforce_profile_completion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_photo_count integer;
  v_interest_count integer;
begin
  select count(*)::integer
  into v_photo_count
  from public.profile_photos
  where profile_id = new.id
    and deleted_at is null;

  select count(*)::integer
  into v_interest_count
  from public.user_interests
  where user_id = new.id;

  new.is_profile_complete := (
    new.first_name is not null
    and btrim(new.first_name) <> ''
    and new.birth_date is not null
    and new.gender is not null
    and cardinality(new.searching_for) between 1 and 5
    and v_photo_count between 2 and 4
    and v_interest_count between 2 and 3
  );

  return new;
end;
$$;

create or replace function private.refresh_profile_from_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.refresh_profile_completion(new.id);
  return new;
end;
$$;

create or replace function private.refresh_profile_from_child()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform private.refresh_profile_completion(old.profile_id);
  else
    perform private.refresh_profile_completion(new.profile_id);
    if tg_op = 'UPDATE' and old.profile_id <> new.profile_id then
      perform private.refresh_profile_completion(old.profile_id);
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create or replace function private.refresh_profile_from_interest()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform private.refresh_profile_completion(old.user_id);
  else
    perform private.refresh_profile_completion(new.user_id);
    if tg_op = 'UPDATE' and old.user_id <> new.user_id then
      perform private.refresh_profile_completion(old.user_id);
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create or replace function private.enforce_active_photo_limit()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_count integer;
begin
  if new.deleted_at is not null then
    return new;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('profile_photos:' || new.profile_id::text, 0)
  );

  select count(*)::integer
  into v_count
  from public.profile_photos
  where profile_id = new.profile_id
    and deleted_at is null
    and id <> new.id;

  if v_count >= 4 then
    raise exception using
      errcode = '23514',
      message = 'a profile can have at most four active photos';
  end if;

  return new;
end;
$$;

create or replace function private.enforce_interest_limit()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_count integer;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('user_interests:' || new.user_id::text, 0)
  );

  select count(*)::integer
  into v_count
  from public.user_interests
  where user_id = new.user_id
    and interest_id <> new.interest_id;

  if v_count >= 3 then
    raise exception using
      errcode = '23514',
      message = 'a profile can have at most three interests';
  end if;

  return new;
end;
$$;

create or replace function private.guard_message_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_match public.matches%rowtype;
  v_duplicate_count integer;
  v_content_hash bytea;
begin
  select *
  into v_match
  from public.matches
  where id = new.match_id
  for share;

  if not found
    or new.sender_id not in (v_match.user_low_id, v_match.user_high_id)
    or v_match.status <> 'active'
  then
    raise exception using
      errcode = '42501',
      message = 'message is not allowed';
  end if;

  if exists (
    select 1
    from public.blocks
    where (blocker_id = v_match.user_low_id and blocked_id = v_match.user_high_id)
       or (blocker_id = v_match.user_high_id and blocked_id = v_match.user_low_id)
  ) then
    raise exception using
      errcode = '42501',
      message = 'message is not allowed';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = new.sender_id
      and account_status = 'active'
  ) then
    raise exception using
      errcode = '42501',
      message = 'message is not allowed';
  end if;

  new.content := btrim(new.content);
  v_content_hash := extensions.digest(
    lower(regexp_replace(new.content, '\s+', ' ', 'g')),
    'sha256'
  );

  select count(*)::integer
  into v_duplicate_count
  from public.messages
  where sender_id = new.sender_id
    and content_hash = v_content_hash
    and created_at >= statement_timestamp() - interval '1 hour';

  if v_duplicate_count >= 5 then
    raise exception using
      errcode = '54000',
      message = 'repeated message limit reached';
  end if;

  return new;
end;
$$;

create or replace function private.guard_message_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.match_id <> old.match_id
    or new.sender_id <> old.sender_id
    or new.content <> old.content
    or new.created_at <> old.created_at
  then
    raise exception using
      errcode = '55000',
      message = 'message content and ownership are immutable';
  end if;

  return new;
end;
$$;

create or replace function private.update_match_last_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.matches
  set last_message_at = new.created_at
  where id = new.match_id;
  return new;
end;
$$;

create or replace function private.guard_report_context()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_match_id uuid;
  v_user_low_id uuid;
  v_user_high_id uuid;
  v_message_sender_id uuid;
begin
  if new.message_id is not null then
    select m.match_id, m.sender_id
    into v_match_id, v_message_sender_id
    from public.messages m
    where m.id = new.message_id;

    if not found
      or v_message_sender_id <> new.reported_user_id
      or (new.match_id is not null and new.match_id <> v_match_id)
    then
      raise exception using
        errcode = '23514',
        message = 'reported message context is invalid';
    end if;

    new.match_id := v_match_id;
  end if;

  if new.match_id is not null then
    select m.user_low_id, m.user_high_id
    into v_user_low_id, v_user_high_id
    from public.matches m
    where m.id = new.match_id;

    if not found
      or new.reporter_id not in (v_user_low_id, v_user_high_id)
      or new.reported_user_id not in (v_user_low_id, v_user_high_id)
    then
      raise exception using
        errcode = '23514',
        message = 'reported match context is invalid';
    end if;
  end if;

  return new;
end;
$$;

create or replace function private.handle_block_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.likes
  set
    status = 'cancelled',
    resolved_at = statement_timestamp()
  where status = 'pending'
    and (
      (sender_id = new.blocker_id and recipient_id = new.blocked_id)
      or (sender_id = new.blocked_id and recipient_id = new.blocker_id)
    );

  update public.matches
  set
    status = 'blocked',
    ended_at = statement_timestamp()
  where status = 'active'
    and user_low_id = case
      when new.blocker_id::text < new.blocked_id::text then new.blocker_id
      else new.blocked_id
    end
    and user_high_id = case
      when new.blocker_id::text < new.blocked_id::text then new.blocked_id
      else new.blocker_id
    end;

  return new;
end;
$$;

create or replace function private.prevent_audit_log_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception using
    errcode = '55000',
    message = 'audit logs are append-only';
end;
$$;

create or replace function private.audit_moderation_action()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.audit_logs (
    actor_id,
    event_type,
    target_table,
    target_id,
    metadata
  )
  values (
    new.moderator_id,
    'moderation.action_created',
    'profiles',
    new.target_user_id,
    jsonb_build_object(
      'action_id', new.id,
      'action_type', new.action_type,
      'report_id', new.report_id
    )
  );

  return new;
end;
$$;

create trigger profiles_validate_age
before insert or update of birth_date, first_name, bio
on public.profiles
for each row execute function private.validate_profile_age();

create trigger profiles_enforce_completion
before insert or update on public.profiles
for each row execute function private.enforce_profile_completion();

create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function private.touch_updated_at();

create trigger profiles_refresh_completion
after insert or update of first_name, birth_date, gender, searching_for
on public.profiles
for each row execute function private.refresh_profile_from_profile();

create trigger profile_photos_enforce_limit
before insert or update of profile_id, deleted_at
on public.profile_photos
for each row execute function private.enforce_active_photo_limit();

create trigger profile_photos_refresh_completion
after insert or update of profile_id, deleted_at or delete
on public.profile_photos
for each row execute function private.refresh_profile_from_child();

create trigger user_interests_enforce_limit
before insert or update of user_id, interest_id
on public.user_interests
for each row execute function private.enforce_interest_limit();

create trigger user_interests_refresh_completion
after insert or update or delete
on public.user_interests
for each row execute function private.refresh_profile_from_interest();

create trigger user_locations_touch_updated_at
before update on public.user_locations
for each row execute function private.touch_updated_at();

create trigger user_presence_touch_updated_at
before update on public.user_presence
for each row execute function private.touch_updated_at();

create trigger matches_touch_updated_at
before update on public.matches
for each row execute function private.touch_updated_at();

create trigger messages_guard_insert
before insert on public.messages
for each row execute function private.guard_message_insert();

create trigger messages_guard_update
before update on public.messages
for each row execute function private.guard_message_update();

create trigger messages_update_match
after insert on public.messages
for each row execute function private.update_match_last_message();

create trigger blocks_apply_immediately
after insert on public.blocks
for each row execute function private.handle_block_insert();

create trigger reports_touch_updated_at
before update on public.reports
for each row execute function private.touch_updated_at();

create trigger reports_guard_context
before insert or update of reporter_id, reported_user_id, match_id, message_id
on public.reports
for each row execute function private.guard_report_context();

create trigger moderation_actions_audit
after insert on public.moderation_actions
for each row execute function private.audit_moderation_action();

create trigger audit_logs_prevent_update
before update or delete on public.audit_logs
for each row execute function private.prevent_audit_log_mutation();

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_auth_user();

create or replace function public.update_my_location(
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_m real default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := statement_timestamp();
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  if p_latitude not between -90 and 90
    or p_longitude not between -180 and 180
    or (p_accuracy_m is not null and p_accuracy_m not between 0 and 10000)
  then
    raise exception using errcode = '22023', message = 'invalid location';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = v_user_id
      and account_status = 'active'
  ) then
    raise exception using errcode = '42501', message = 'location update is not allowed';
  end if;

  insert into public.user_locations (
    user_id,
    location,
    accuracy_m,
    captured_at,
    expires_at
  )
  values (
    v_user_id,
    extensions.st_setsrid(
      extensions.st_makepoint(p_longitude, p_latitude),
      4326
    )::extensions.geography,
    p_accuracy_m,
    v_now,
    v_now + interval '15 minutes'
  )
  on conflict (user_id) do update
  set
    location = excluded.location,
    accuracy_m = excluded.accuracy_m,
    captured_at = excluded.captured_at,
    expires_at = excluded.expires_at;
end;
$$;

create or replace function public.activate_presence(
  p_mood public.mood,
  p_duration_minutes smallint default 60
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := statement_timestamp();
  v_available_until timestamptz;
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  if p_duration_minutes not between 15 and 240 then
    raise exception using errcode = '22023', message = 'availability duration must be between 15 and 240 minutes';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = v_user_id
      and account_status = 'active'
      and is_profile_complete
  ) or not exists (
    select 1
    from public.user_locations
    where user_id = v_user_id
      and expires_at > v_now
  ) then
    raise exception using errcode = '42501', message = 'presence activation is not allowed';
  end if;

  v_available_until := v_now + make_interval(mins => p_duration_minutes);

  insert into public.user_presence (
    user_id,
    availability_status,
    mood,
    last_heartbeat_at,
    activated_at,
    available_until
  )
  values (
    v_user_id,
    'available',
    p_mood,
    v_now,
    v_now,
    v_available_until
  )
  on conflict (user_id) do update
  set
    availability_status = 'available',
    mood = excluded.mood,
    last_heartbeat_at = excluded.last_heartbeat_at,
    activated_at = excluded.activated_at,
    available_until = excluded.available_until;

  return v_available_until;
end;
$$;

create or replace function public.heartbeat_presence()
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_available_until timestamptz;
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  update public.user_presence
  set last_heartbeat_at = statement_timestamp()
  where user_id = v_user_id
    and availability_status = 'available'
    and available_until > statement_timestamp()
  returning available_until into v_available_until;

  if v_available_until is null then
    raise exception using errcode = '55000', message = 'presence is not active';
  end if;

  return v_available_until;
end;
$$;

create or replace function public.deactivate_presence(p_hidden boolean default false)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  insert into public.user_presence (user_id, availability_status)
  values (
    v_user_id,
    case when p_hidden then 'hidden'::public.availability_status else 'offline'::public.availability_status end
  )
  on conflict (user_id) do update
  set
    availability_status = excluded.availability_status,
    mood = null,
    last_heartbeat_at = statement_timestamp(),
    activated_at = null,
    available_until = null;

  delete from public.user_locations where user_id = v_user_id;
end;
$$;

create or replace function public.get_nearby_profiles(
  p_radius_m integer default 5000,
  p_limit integer default 20
)
returns table (
  profile_id uuid,
  first_name text,
  age smallint,
  bio text,
  gender public.gender,
  mood public.mood,
  distance_band public.distance_band,
  primary_photo_url text,
  interest_slugs text[]
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  if p_radius_m <> all (array[1000, 3000, 5000, 10000])
    or p_limit not between 1 and 50
  then
    raise exception using errcode = '22023', message = 'invalid discovery parameters';
  end if;

  return query
  with me as (
    select
      l.location,
      p.gender,
      p.searching_for
    from public.user_locations l
    join public.profiles p on p.id = l.user_id
    where l.user_id = v_user_id
      and l.expires_at > statement_timestamp()
      and p.account_status = 'active'
  ),
  candidates as (
    select
      p.id,
      p.first_name,
      extract(year from age(current_date, p.birth_date))::smallint as public_age,
      p.bio,
      p.gender,
      pr.mood,
      extensions.st_distance(l.location, me.location) as distance_m
    from me
    join public.user_locations l
      on extensions.st_dwithin(l.location, me.location, p_radius_m)
    join public.profiles p on p.id = l.user_id
    join public.user_presence pr on pr.user_id = p.id
    where p.id <> v_user_id
      and l.expires_at > statement_timestamp()
      and p.account_status = 'active'
      and p.is_discoverable
      and p.is_profile_complete
      and p.birth_date is not null
      and p.gender is not null
      and p.gender = any (me.searching_for)
      and me.gender = any (p.searching_for)
      and pr.availability_status = 'available'
      and pr.available_until > statement_timestamp()
      and pr.last_heartbeat_at >= statement_timestamp() - interval '5 minutes'
      and not exists (
        select 1
        from public.blocks b
        where (b.blocker_id = v_user_id and b.blocked_id = p.id)
           or (b.blocker_id = p.id and b.blocked_id = v_user_id)
      )
  )
  select
    c.id,
    c.first_name,
    c.public_age,
    c.bio,
    c.gender,
    c.mood,
    case
      when c.distance_m < 150 then 'TOUT_PRES'::public.distance_band
      when c.distance_m < 500 then 'MOINS_DE_500_M'::public.distance_band
      when c.distance_m < 1000 then 'ENTRE_500_M_ET_1_KM'::public.distance_band
      else 'DANS_TON_SECTEUR'::public.distance_band
    end,
    photo.secure_url,
    coalesce(interests.slugs, '{}'::text[])
  from candidates c
  left join lateral (
    select pp.secure_url
    from public.profile_photos pp
    where pp.profile_id = c.id
      and pp.deleted_at is null
    order by pp.sort_order
    limit 1
  ) photo on true
  left join lateral (
    select array_agg(i.slug order by i.slug) as slugs
    from public.user_interests ui
    join public.interests i on i.id = ui.interest_id
    where ui.user_id = c.id
      and i.is_active
  ) interests on true
  order by md5(
    c.id::text
    || v_user_id::text
    || floor(extract(epoch from statement_timestamp()) / 900)::text
  )
  limit p_limit;
end;
$$;

create or replace function public.send_hello(p_recipient_id uuid)
returns table (
  like_id uuid,
  match_id uuid,
  is_match boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sender_id uuid := auth.uid();
  v_like_id uuid;
  v_reciprocal_like_id uuid;
  v_match_id uuid;
  v_user_low_id uuid;
  v_user_high_id uuid;
  v_daily_limit integer := 25;
begin
  if v_sender_id is null then
    raise exception using errcode = '28000', message = 'authentication required';
  end if;

  if p_recipient_id is null or p_recipient_id = v_sender_id then
    raise exception using errcode = '22023', message = 'invalid recipient';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      least(v_sender_id::text, p_recipient_id::text)
      || ':'
      || greatest(v_sender_id::text, p_recipient_id::text),
      0
    )
  );

  if not exists (
    select 1
    from public.profiles
    where id = v_sender_id
      and account_status = 'active'
      and is_profile_complete
  ) or not exists (
    select 1
    from public.user_presence
    where user_id = v_sender_id
      and availability_status = 'available'
      and available_until > statement_timestamp()
      and last_heartbeat_at >= statement_timestamp() - interval '5 minutes'
  ) or not exists (
    select 1
    from public.profiles
    where id = p_recipient_id
      and account_status = 'active'
      and is_profile_complete
  ) or not exists (
    select 1
    from public.user_presence
    where user_id = p_recipient_id
      and availability_status = 'available'
      and available_until > statement_timestamp()
      and last_heartbeat_at >= statement_timestamp() - interval '5 minutes'
  ) then
    raise exception using errcode = '42501', message = 'hello request is not allowed';
  end if;

  if exists (
    select 1
    from public.blocks
    where (blocker_id = v_sender_id and blocked_id = p_recipient_id)
       or (blocker_id = p_recipient_id and blocked_id = v_sender_id)
  ) then
    raise exception using errcode = '42501', message = 'hello request is not allowed';
  end if;

  if exists (
    select 1
    from public.likes
    where sender_id = v_sender_id
      and recipient_id = p_recipient_id
      and status = 'pending'
  ) then
    raise exception using errcode = '23505', message = 'a hello request is already pending';
  end if;

  if (
    select count(*)
    from public.likes
    where sender_id = v_sender_id
      and created_at >= statement_timestamp() - interval '1 hour'
  ) >= 5 then
    raise exception using errcode = '54000', message = 'hourly hello limit reached';
  end if;

  select coalesce((value #>> '{}')::integer, 25)
  into v_daily_limit
  from private.app_settings
  where key = 'hello_daily_limit';

  v_daily_limit := coalesce(v_daily_limit, 25);

  if (
    select count(*)
    from public.likes
    where sender_id = v_sender_id
      and created_at >= date_trunc('day', statement_timestamp())
  ) >= v_daily_limit then
    raise exception using errcode = '54000', message = 'daily hello limit reached';
  end if;

  insert into public.likes (sender_id, recipient_id)
  values (v_sender_id, p_recipient_id)
  returning id into v_like_id;

  select id
  into v_reciprocal_like_id
  from public.likes
  where sender_id = p_recipient_id
    and recipient_id = v_sender_id
    and status = 'pending'
  order by created_at desc
  limit 1
  for update;

  if v_reciprocal_like_id is null then
    return query select v_like_id, null::uuid, false;
    return;
  end if;

  if v_sender_id::text < p_recipient_id::text then
    v_user_low_id := v_sender_id;
    v_user_high_id := p_recipient_id;
  else
    v_user_low_id := p_recipient_id;
    v_user_high_id := v_sender_id;
  end if;

  insert into public.matches (user_low_id, user_high_id)
  values (v_user_low_id, v_user_high_id)
  on conflict (user_low_id, user_high_id) do update
  set
    status = 'active',
    matched_at = statement_timestamp(),
    ended_at = null
  returning id into v_match_id;

  update public.likes
  set
    status = 'matched',
    matched_at = statement_timestamp()
  where id in (v_like_id, v_reciprocal_like_id);

  return query select v_like_id, v_match_id, true;
end;
$$;

create or replace function public.expire_stale_presence()
returns table (
  presences_expired integer,
  locations_deleted integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_presences integer;
  v_locations integer;
begin
  update public.user_presence
  set
    availability_status = 'offline',
    mood = null,
    activated_at = null,
    available_until = null
  where availability_status = 'available'
    and (
      available_until <= statement_timestamp()
      or last_heartbeat_at < statement_timestamp() - interval '5 minutes'
    );

  get diagnostics v_presences = row_count;

  delete from public.user_locations
  where expires_at <= statement_timestamp();

  get diagnostics v_locations = row_count;
  return query select v_presences, v_locations;
end;
$$;

alter table public.profiles enable row level security;
alter table public.profile_photos enable row level security;
alter table public.interests enable row level security;
alter table public.user_interests enable row level security;
alter table public.user_locations enable row level security;
alter table public.user_presence enable row level security;
alter table public.likes enable row level security;
alter table public.matches enable row level security;
alter table public.messages enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.user_locations from anon, authenticated;
revoke all on table private.app_settings from public, anon, authenticated;

revoke all on all functions in schema private from public, anon, authenticated;

revoke all on function public.update_my_location(double precision, double precision, real)
  from public, anon, authenticated;
revoke all on function public.activate_presence(public.mood, smallint)
  from public, anon, authenticated;
revoke all on function public.heartbeat_presence()
  from public, anon, authenticated;
revoke all on function public.deactivate_presence(boolean)
  from public, anon, authenticated;
revoke all on function public.get_nearby_profiles(integer, integer)
  from public, anon, authenticated;
revoke all on function public.send_hello(uuid)
  from public, anon, authenticated;
revoke all on function public.expire_stale_presence()
  from public, anon, authenticated;

grant execute on function public.update_my_location(double precision, double precision, real)
  to authenticated;
grant execute on function public.activate_presence(public.mood, smallint)
  to authenticated;
grant execute on function public.heartbeat_presence()
  to authenticated;
grant execute on function public.deactivate_presence(boolean)
  to authenticated;
grant execute on function public.get_nearby_profiles(integer, integer)
  to authenticated;
grant execute on function public.send_hello(uuid)
  to authenticated;
grant execute on function public.expire_stale_presence()
  to service_role;
